apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-router
spec:
  serviceName: svc-router
  replicas: 1
  selector:
    matchLabels:
      app: deploy-api
  template:
    metadata:
      labels:
        app: deploy-api
    spec:
      containers:
        - name: router
          image: gcr.io/aesthetic-vent-494006-g0/router:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: svc-router
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: svc-router
      spec:
        accessModes: 
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
