apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-storage
spec:
  serviceName: svc-storage
  replicas: 1
  selector:
    matchLabels:
      app: deploy-api
  template:
    metadata:
      labels:
        app: deploy-api
    spec:
      containers:
        - name: storage
          image: gcr.io/aesthetic-vent-494006-g0/backend-storage:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: svc-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: svc-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
